// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"
	models "gophermart-loyalty/internal/models"

	mock "github.com/stretchr/testify/mock"
)

// UpdateFunc is an autogenerated mock type for the UpdateFunc type
type UpdateFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: ctx, operation
func (_m *UpdateFunc) Execute(ctx context.Context, operation *models.Operation) error {
	ret := _m.Called(ctx, operation)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Operation) error); ok {
		r0 = rf(ctx, operation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewUpdateFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewUpdateFunc creates a new instance of UpdateFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUpdateFunc(t mockConstructorTestingTNewUpdateFunc) *UpdateFunc {
	mock := &UpdateFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
