version: "2.4"
services:

  ###
  # Балансировщик
  ###
  loadbalancer:
    build: loadbalancer
    ports:
      - "80:80"
    depends_on:
      gophermart:
        condition: service_started

  ###
  # Накопительная система лояльности
  ###
  gophermart:
    build: ../..
    scale: 3 # <- Запускается 3 экземпляра сервиса
    environment:
      RUN_ADDRESS: 0.0.0.0:8080
      DATABASE_URI: postgres://gophermart:${GOPHERMART_PG_PASSWORD}@db:5432/gophermart
      ACCRUAL_SYSTEM_ADDRESS: http://accrual:8080
      ACCRUAL_SYSTEM_POLL_INTERVAL: 1s
      AUTH_SECRET: ${GOPHERMART_AUTH_SECRET}
    depends_on:
        db:
          condition: service_healthy
        accrual:
          condition: service_started

  ###
  # База данных накопительной системы лояльности
  ###
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: gophermart
      POSTGRES_PASSWORD: ${GOPHERMART_PG_PASSWORD}
      POSTGRES_DB: gophermart
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 5s
      retries: 5

  ###
  # Система расчета баллов лояльности
  ###
  accrual:
    build: ../../cmd/accrual
    environment:
      - RUN_ADDRESS=0.0.0.0:8080

  ###
  # Наполнение данными системы расчета баллов лояльности
  ###
  accrual-populate:
    build: accrual-populate
    depends_on:
      accrual:
        condition: service_started
