version: "3"
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: autotest
      POSTGRES_PASSWORD: autotest
      POSTGRES_DB: autotest
    volumes:
      - ../../testdata/autotest-postgres:/var/lib/postgresql/data
